#include "lib.h"

//dari componen.c
void btn_hover(x, y, textbtn);
void btn_iddle(const char* text);
void frisa();
void backgroundcolor(new_color);
void rgbtext(rt, gt, bt);
void rgbbgt(rb, gb, bb);
void posisi(x, y);
void kotak(panjang, lebar, x, y, rdal, gdal, bdal, rlu, glu, blu);
void resetcolor();
void resetbg();
void tekswarna(textcolor, bgtext);
void borderhorizontal(x, y, type);
void bordertop();
void borderutama();
void border();
void tampilmenurole(pilihanrole);
void pilihrole();
int menu_role();
void loginadmin();
void tampilmenuutama(pilihan);
void tampilbuttonuser(pilihan);
int formlogin_admin();
void tampilbuttonadmin(pilihan);
int menu_user();
int menu_admin(defaultPilihan);
int menu_utama();
void bordercs(panjang, lebar, x, y, rdal, gdal, bdal, rlu, glu, blu);
void ambulance1(r, g, b, x, y, rdal, gdal, bdal);
int daftar();
void daftarlogo(x, y);
int formdaftar();
int formlogin();
void warning_daftar();
void loginuser();
void mailput();
void loginlogo();
void starshow();
void halamanuser();
void ambiltanggal();
void logout();
void tampilanpanggil();
void aksipanggil();
void tampilanhistori();
void halamanadmin();
void tampilandashboard();
void tampilanakun();
void tambah_user();
void edit_user();
void tambah_supir();
void edit_supir();
void hapus_supir();
void tambah_admin();
void edit_admin();
void hapus_admin();
int menu_akun();
void submenu_akun(pilihanMenu);
void tampil_user(x, y);
void tampil_supir(x, y);
void tampil_admin(x, y);
void menuakunabal();
void tampil_semua_user(x, y);
void tampil_semua_supir(x, y);
void tampil_semua_admin(x, y);
int hitung_total_user();
int hitung_total_rs();
int hitung_total_ambulans();
int hitung_total_laporan();
void tambah_admin();
void edit_admin();
void hapus_admin();
void tampilan_ambulans();
int menu_ambulans();
void menu_ambulansabal();
void tampil_menu_ambulans(pilihanMenu);
void tambah_ambulans();
void edit_ambulans();
void hapus_ambulans();
void panggil();
int pilih_rs();
void laporan();
void tampilanlaporan();
void tampilan_profil_user();
void menu_rumah_sakit();
void tampil_menu_rs(pilihanMenu);
void menurshover();
int about(const char* nama_file);
int menu_supir();
void halamansupir();
void tampilbuttonsupir(pilihan);
void loginsupir();
int formloginsupir();
void aksi_tugas_supir();
void keputusan_supir(id_laporan);

//stop
void end();